chore(deps): Upgrade alloy to 0.11
Cannot upgrade to 0.12 at the moment, due to following error in a
dependency of alloy:

```
error[E0599]: no function or associated item named `hoodi` found for struct `alloy_chains::Chain` in the current scope
   --> /home/stan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-hardforks-0.1.1/src/hardfork/ethereum.rs:63:28
    |
63  |         if chain == Chain::hoodi() {
    |                            ^^^^^ function or associated item not found in `Chain`
    |
```